"""empty message

Revision ID: 15685d598198
Revises: 349ff4ab5047
Create Date: 2023-12-01 09:21:15.858691

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '15685d598198'
down_revision: Union[str, None] = '349ff4ab5047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
