"""empty message

Revision ID: 18491b77276a
Revises: edad346bb25b
Create Date: 2023-12-01 09:14:22.533800

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '18491b77276a'
down_revision: Union[str, None] = 'edad346bb25b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_by',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('updated_by',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('deleted_by',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('giant', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_by',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('updated_by',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('deleted_by',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('giant_tag', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_by',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('updated_by',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('deleted_by',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('giant_tag_assoc', schema=None) as batch_op:
        batch_op.alter_column('giant_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('tag_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('giant_tag_assoc', schema=None) as batch_op:
        batch_op.alter_column('tag_id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('giant_id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)

    with op.batch_alter_table('giant_tag', schema=None) as batch_op:
        batch_op.alter_column('deleted_by',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('updated_by',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('giant', schema=None) as batch_op:
        batch_op.alter_column('deleted_by',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('updated_by',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.alter_column('deleted_by',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('updated_by',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
