"""empty message

Revision ID: edad346bb25b
Revises: fbf5aec38d68
Create Date: 2023-12-01 08:56:51.377669

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'edad346bb25b'
down_revision: Union[str, None] = 'fbf5aec38d68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ename', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['author.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['author.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('giant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('twitter_x', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['author.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['author.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('giant_tag',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['author.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['author.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('giant_tag_assoc',
    sa.Column('giant_id', sa.Uuid(), nullable=True),
    sa.Column('tag_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['giant_id'], ['giant.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['giant_tag.id'], ),
    sa.UniqueConstraint('giant_id', 'tag_id', name='giant_tag_assoc_uq_1')
    )
    op.drop_table('giants')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('giants',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('giant_tag_assoc')
    op.drop_table('giant_tag')
    op.drop_table('giant')
    op.drop_table('author')
    # ### end Alembic commands ###
