"""empty message

Revision ID: fbf5aec38d68
Revises: 
Create Date: 2023-12-01 07:53:06.987326

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fbf5aec38d68'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('giants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('schema_migration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schema_migration',
    sa.Column('onerow_id', sa.BOOLEAN(), server_default=sa.text('(TRUE)'), nullable=True),
    sa.Column('data_loaded', sa.BOOLEAN(), nullable=False),
    sa.Column('version', sa.INTEGER(), nullable=False),
    sa.CheckConstraint('onerow_id', name='onerow_uni'),
    sa.PrimaryKeyConstraint('onerow_id')
    )
    op.drop_table('giants')
    # ### end Alembic commands ###
